### ISSUE TITLE
安装 node-sass 的正确姿势

### ISSUE THREAD

**Issue by lmk123** [lmk123/blog#28]
安装 [node-sass](https://github.com/sass/node-sass) 的时候总是会各种不成功，今天我琢磨了一会儿总算知道要怎么解决了。

首先要知道的是，安装 node-sass 时在 `node scripts/install` 阶段会从 github.com 上下载一个 `.node` 文件，大部分安装不成功的原因都源自这里，因为 github Releases 里的文件都托管在 `github-cloud.s3.amazonaws.com` 上面，而这个网址在国内总是_网络不稳定_，所以我们需要通过第三方服务器下载这个文件。（顺带一提，你可以看看[这个好玩的 commit](https://github.com/sass/node-sass/commit/b8050efbe0effb68b0617d28276c72eef1fb15ef)）

假设你的高科技在你本地机器上开启了一个第三方服务器 `127.0.0.1:1080`，那么只需按照下面的方法配置一下就能正常安装 `node-sass` 了（如果你开启的是 PAC 模式而不是全局模式，那还需要将 `github-cloud.s3.amazonaws.com` 加入 PAC 列表）：

```
npm config set proxy http://127.0.0.1:1080
npm i --save-dev node-sass

# 下载完成后删除 http 代理
npm config delete proxy
```

嗯，这样下来就能正常安装了。

**Comment by 1340641314** [comment]
卧槽，搞了一个下午，还是楼主的第一条管用

**Comment by lmk123** [comment]
@1340641314 哈哈，我当初也是搞了一下午才弄明白

**Comment by 1340641314** [comment]
@lmk123 669

**Comment by motorguo** [comment]
卧槽，我也是搞了一下午

**Comment by wanming** [comment]
![alec-baldwin-approval-Cgo9XkgzRcTPW](https://media3.giphy.com/media/Cgo9XkgzRcTPW/giphy.gif)

**Comment by megone** [comment]
楼主威武

**Comment by dear-lizhihua** [comment]
方法3 cnpm安装，淘宝做了node-sass的镜像
https://cnodejs.org/topic/5637549fd426a1404cbd0614

有些node包依赖于phantom，安装也会失败，同样解决办法也是cnpm安装

**Comment by lmk123** [comment]
@dear-lizhihua 我的做法是在项目内添加一个 `.npmrc` 文件：

```
phantomjs_cdnurl=http://cnpmjs.org/downloads
sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
registry=https://registry.npm.taobao.org
```

这样使用 `npm install` 安装 node-sass 和 phantomjs 时都能自动从淘宝源上下载，但是在使用`npm publish` 的时候要把 `registry` 这一行给注释掉，否则就会发布到淘宝源上去了。

**Comment by yyzych** [comment]
楼主大发！

**Comment by xiaofuyesnew** [comment]
对windows下的同学如果第一种办法无效的话可以拆分成两个命令
```
set SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
npm install node-sass
```
然后每次安装之前都要set一下。秒装。

**Comment by paysage** [comment]
请问对应的依赖也会一起安装吗? 还是还得单独安装？

**Comment by xiaofuyesnew** [comment]
@paysage 不需要单独安装，如果依赖中有node-sass的话，直接在`npm install`前面加`SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/`
也就是这样：
```
SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install
```
在遇到node-sass的二进制文件时，会自动从淘宝的镜像里面开始下载。

结论： node-sass不需要单独安装

**Comment by xhlwill** [comment]
windows下在 git bash 窗口里（前提是安装了git）也可以直接运行这条命令
```
SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ npm install node-sass
```
因为安装git就同时为windows安装了一个gnu环境 - mingw

**Comment by xiaofuyesnew** [comment]
@xhlwill 对，但是个人觉得git bash在win环境下的运行效率有点低，毕竟是杂交的环境。
用Cmder的话更快一点，也兼容了大部分bash命令。

**Comment by leiboo** [comment]
给大神跪了，搞了一上午，还是第一种方法管用。

**Comment by xhlwill** [comment]
@xiaofuyesnew 用了Cmder 也感觉很慢 TT

**Comment by zicongxie** [comment]
well done!

**Comment by hy-inger** [comment]
第一种方法管用。楼主威武。

**Comment by hardmen** [comment]
第一种方法有用

**Comment by nellochen** [comment]
卧槽，前来报到，被坑了。。。一直提示.net framework的问题，windows 10系统标识蛋疼，第一种方法可行！

**Comment by yifeikong** [comment]
谢谢楼主，每当遇到这种问题，就想骂一句「他喵的方滨兴」

**Comment by onlywhite** [comment]
SASS_BINARY_SITE不是内部命令是怎么回事啊

**Comment by xhlwill** [comment]
具体怎么出现报错

**Comment by krystalcl** [comment]
楼主666

**Comment by krystalcl** [comment]
正好遇到这个问题，感谢感谢

**Comment by xhlwill** [comment]
@onlywhite set设置的环境变量只在当前console生效，只是临时的，要永久用setx

**Comment by yin-fan** [comment]
感谢楼主，问题解决了

**Comment by wq1308786830** [comment]
喜欢第二种方式，很不错

**Comment by andyiac** [comment]
使用梯子还有一种一劳永逸的姿势：

安装配置下 proxychains4 

```
brew install proxychains-ng
```
在配置文件 
```
/usr/local/etc/proxychains.conf
```
下添加一行

```
socks5  127.0.0.1 1080
```
然后
```
proxychains4 npm install 
```

以后下载被河蟹的内容加上 `proxychains4` 就行了

**Comment by revanli** [comment]
各种google, 后来用中文搜一下，找到这里，第一条管用，蛋疼的问题

**Comment by feizhen** [comment]
其实可以安装cnpm，然后使用cnpm来安装就好了

**Comment by fanerge** [comment]
我是用方法三弄好了，社区的力量强大

**Comment by yl1003** [comment]
方法1直接就可以了

**Comment by delsedin** [comment]
感谢感谢，用方法1终于搞定。

**Comment by zhaoboxiang** [comment]
感谢感谢感谢！折腾半天了！楼主威武！方法一弄好的

**Comment by xiaozhouwu** [comment]
good

**Comment by PiscesKnight** [comment]
用的第二个方法，超感谢，折腾老半天

**Comment by Vivomo** [comment]
### 用的第二个方法, 感激涕零

**Comment by LiuSuY** [comment]
感谢楼主，帮助我很容易解决了这个问题

**Comment by soarpatriot** [comment]
🙏 感谢

**Comment by LiuSuY** [comment]
现在可以使用yarn安装也可以解决这个问题

**Comment by nonlau** [comment]
windows下，拆分命令后，还是不行
$ npm install node-sass

> node-sass@4.7.2 install E:\workSpace\nonlau\hexo\node_modules\node-sass
> node scripts/install.js

'node' ▒▒▒▒▒ڲ▒▒▒▒ⲿ▒▒▒Ҳ▒▒▒ǿ▒▒▒▒еĳ▒▒▒
▒▒▒▒▒▒▒▒▒ļ▒▒▒
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fseven1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x6)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 install script.

**Comment by LiuSuY** [comment]
你可以试试yarn add  node-sass

**Comment by Yapril** [comment]
用git终端 npm install node-sass  一次搞定~

**Comment by LiuSuY** [comment]
1 . node -p "[process.platform, process.arch, process.versions.modules].join('-')"
2. set SASS_BINARY_PATH=D:/nodejs/.nodes/win32-x64-57_binding.node
3. npm install node-sass

**Comment by morenyang** [comment]
使用yarn的话可以把下面这一行代码加入到.yarnrc里面 mac实测秒载
`sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"`

**Comment by vv314** [comment]
`npm config set sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"`

yarn 的 config  会继承 npm 的 config，所以只用设置 npm  的映射就行，
当然，如果不放心也可以:

`yarn config set sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"`

上述命令其实就通过命令方式是改了 `.npmrc` 和 `.yarnrc`，和手动修改是等价的。

**Comment by jerry9926** [comment]
卧槽，搞了一个下午，还是楼主的第一条管用 +1

**Comment by JSoon** [comment]
mark

**Comment by yexk** [comment]
```

gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '10.1.0' ]
gyp verb install input version string "10.1.0"
gyp verb install installing version: 10.1.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.1.0
gyp verb ensuring nodedir is created /www/project/node_modules/node-sass/.node-gyp/10.1.0
gyp WARN EACCES user "root" does not have permission to access the dev dir "/www/project/node_modules/node-sass/.node-gyp/10.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/www/project/node_modules/node-sass/.node-gyp"
```
大佬。centos 7.2 ,node v10.1.0 npm 5.6.0 淘宝源。。这个错误怎么解决？？

**Comment by hucheng91** [comment]
发现其实在github下不到，是会去本地的 `Users\user\AppData\Roaming\npm-cache\node-sass(比方，我电脑用户名叫 hc，一般在c:\Users\user\AppData\Roaming\npm-cache\node-sass`)这个目录找，那解决办法就是，先去https://github.com/sass/node-sass/releases,将需要的*_binding.node下载下来，放到本地对应目录就好

**Comment by ShumRain** [comment]
非常感谢！

**Comment by tsingroo** [comment]
Ubuntu下使用如下命令设置NodeSass源
`export SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/`

**Comment by codevvvv9** [comment]
我是deepin linux系统。
方法一之前用的deeepin 15.7能行，现在重装15.8完后竟然淘宝源都下载不了，重启无数遍，仍然无法下载，宣告失败。
方法二：我买的ss，可以FQ，npm设置代理,全局系统代理却没用，宣告失败。
只能通过下载.node文件安装。
前辈遇到过我这种问题吗，真是醉醉的了

**Comment by codevvvv9** [comment]
@tsingroo 我的淘宝源竟然都不行……

**Comment by tsingroo** [comment]
> @tsingroo 我的淘宝源竟然都不行……

没用过deepin，不太清楚

**Comment by DarrenHou1993** [comment]
这种方式只有npm install node-sass 指定单独安装某个时才行。如何npm install 所有依赖的时候。使用淘宝源。目前我发现在安装到node-sass的时候，还是从github上拉取。。。

**Comment by HTPAUN** [comment]
谢谢！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊！！！！！！！！！！！！我装不了自闭了一天！！！！！！！！！！！！！我用的



对windows下的同学如果第一种办法无效的话可以拆分成两个命令

set SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
npm install node-sass
然后每次安装之前都要set一下。秒装。




这个方法！

**Comment by llyer** [comment]
好用

**Comment by KilFront** [comment]
我太难了，从楼上试到楼下
binding.target.mk:131: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/d/code/apowo/platform-client/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/d/code/apowo/platform-client/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/d/code/apowo/platform-client/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /d/code/apowo/platform-client/node_modules/node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by cnscorpions** [comment]
环境的问题，要足够淡定 @HTPAUN

**Comment by LinZhaoguan** [comment]
mark

**Comment by djkloop** [comment]
https://www.npmjs.com/package/mirror-config-china

**Comment by frei-x** [comment]
mark

**Comment by webszy** [comment]
npm i node-sass --SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/

**Comment by 13241491189** [comment]
牛逼，折腾了好一会儿总算解决了！

**Comment by Yuhemei** [comment]
node V14.15.3 install success

**Comment by tofrankie** [comment]
> `npm config set sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"`
> 
> yarn 的 config 会继承 npm 的 config，所以只用设置 npm 的映射就行， 当然，如果不放心也可以:
> 
> `yarn config set sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"`
> 
> 上述命令其实就通过命令方式是改了 `.npmrc` 和 `.yarnrc`，和手动修改是等价的。

自 yarn v2 起，就不能从 `.npmrc` 读取配置作为补充了，👉 [Don't use .npmrc files](https://yarnpkg.com/getting-started/migration#dont-use-npmrc-files)。

**Comment by komagic** [comment]
2024 年了，应该是

`sass_binary_site=https://npmmirror.com/mirrors/node-sass/`

**Comment by zhouyu1993** [comment]
已收到。谢谢，我会尽快回复你。

**Comment by csssevenday** [comment]
我在本地安装成功了，但是在gitlab ci/cd 中失败，附图
![1722423330696](https://github.com/user-attachments/assets/ff5c7abc-a2c1-42d1-9ffd-8bd2fd0a1459)
![企业微信截图_1722423381201](https://github.com/user-attachments/assets/95fd73af-bd4f-416b-b797-9b4bf2ee1379)
![企业微信截图_17224234384797](https://github.com/user-attachments/assets/fd147e7b-95ed-4b6b-9bd2-7fb467ef7842)
